# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rails', '>= 7.0'
gem 'sqlite3', '>= 2.1'
gem 'puma'
gem 'sprockets-rails'
gem 'sassc-rails'

gem 'datatables-factory', path: '../..'
gem 'ajax-datatables-rails'
gem 'simple_form'
gem 'faker'

group :test do
  gem 'rspec-rails'
  gem 'capybara'
  gem 'cuprite'
  gem 'database_cleaner-active_record'
end
